spring.datasource.url=jdbc:postgresql://localhost:5433/resume_db
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=your_api_key

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true